version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    container_name: express-app
    ports:
      - "5000:5000"
    environment:   
      - MONGO_URI=mongodb://10.0.1.179:27017/blog-app
    #depends_on:
    #  mongo:
    #    condition: service_healthy
  # mongo:
    # image: mongo:latest
    # container_name: mongo-container
    # ports:
      # - "27017:27017"
    # healthcheck:
      # test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      # interval: 10s
      # # timeout: 5s
      # retries: 5

