version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    container_name: express-app
    ports:
      - "5000:5000"
    environment:   
      - MONGO_URI=mongodb://mongo:27017/blog-app
    depends_on:
       - mongo
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"